version: "3.9"

services:

  ####################################################################################
  # api
  ####################################################################################
  api:
    container_name: pulse-api
    build:
      context: .
      target: exec
      dockerfile: ./docker/app.dockerfile
    image: pulse-api-prod:latest
    env_file: .env
    ports:
      - "9091:9091"
    volumes:
      - .:/pulse-api
    depends_on:
      - postgres

  ####################################################################################
  #  postgres
  ####################################################################################
  postgres:
    container_name: pulse_timescale_db
    image: 'timescale/timescaledb-ha:pg14-latest'
    # By default, a Postgres database is running on the 5432 port.
    # If we want to access the database from our computer (outside the container),
    # we must share the port with our computer's port.
    # The syntax is [port we want on our machine]:[port we want to retrieve in the container]
    ports:
      - "5432:5432"
    env_file: .env
    volumes:
      - postgres:/var/lib/postgresql/data
    command: postgres -c max_wal_size=2GB
    restart: always

# persisted storage
volumes:
  postgres: