version: '3'

services:
  ####################################################################################
  # timescale
  ####################################################################################
  timescale_testing:
    container_name: timescale_testing
    image: 'timescale/timescaledb-ha:pg14-latest'
    env_file:
      - .env
    expose:
      - "5433" # Publishes 5433 to other containers but NOT to host machine
    ports:
      - "5433:5433"
    volumes:
      - postgres:/var/lib/postgresql/data
    command: postgres -c max_wal_size=2GB -p 5433
    networks:
      - test-net

  ####################################################################################
  # pulse api
  ####################################################################################
  testing-pulse-api:
    container_name: testing-pulse-api
    image: mhamm84/pulse-api
    env_file:
      - .env
    ports:
      - 9081:9091
    networks:
      - test-net
    depends_on:
      - timescale_testing

####################################################################################
#networks
####################################################################################
networks:
  test-net:

####################################################################################
#volumes
####################################################################################
volumes:
  postgres:
