version: '3'

services:
  ####################################################################################
  # timescale
  ####################################################################################
  testingDB:
    container_name: timescale_testing
    image: 'timescale/timescaledb-ha:pg14-latest'
    env_file:
      - .env
    ports:
      - 5433:5432
    volumes:
      - postgres:/var/lib/postgresql/data
    command: postgres -c max_wal_size=2GB
    networks:
      - test-net

  ####################################################################################
  # pulse api
  ####################################################################################
  testing-pulse-api:
    container_name: testing-pulse-api
    image: mhamm84/pulse-api
    env_file:
      - .env
    ports:
      - 9081:9091
    networks:
      - test-net
    depends_on:
      - timescale_testing

####################################################################################
#networks
####################################################################################
networks:
  test-net:
    driver: bridge

####################################################################################
#volumes
####################################################################################
volumes:
  postgres:
