version: '3'

services:
  ####################################################################################
  # timescale
  ####################################################################################
  testingDB:
    container_name: timescale_testing
    image: 'timescale/timescaledb-ha:pg14-latest'
    environment:
      POSTGRES_USER: pulse_user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: pulse_testing
    ports:
      - "5433:5432"
    command: postgres -c max_wal_size=2GB