version: '3'

services:
  ####################################################################################
  # timescale
  ####################################################################################
  database:
    container_name: timescale_testing
    image: 'timescale/timescaledb-ha:pg14-latest'
    environment:
      - POSTGRES_DB=testing
      - POSTGRES_USER=testing
      - POSTGRES_PASSWORD=testing-pass
    ports:
      - "5532:5432"
    command: postgres -c max_wal_size=2GB
