version: '3'


####################################################################################
#services
# 1 service = 1 container.
####################################################################################
services:
  ####################################################################################
  # timescale
  ####################################################################################
  database:
    # Official Postgres image from DockerHub (we use the last version)
    image: 'timescale/timescaledb-ha:pg14-latest'
    # By default, a Postgres database is running on the 5432 port.
    # If we want to access the database from our computer (outside the container),
    # we must share the port with our computer's port.
    # The syntax is [port we want on our machine]:[port we want to retrieve in the container]

    # The `env_file` tag allows us to declare an environment file
    env_file:
    - .env
    ports:
      - 5432:5432
    volumes:
      - postgres:/var/lib/postgresql/data
    command: postgres -c max_wal_size=2GB
    restart: always

  ####################################################################################
  # pgadmin
  ####################################################################################
  pgadmin:
    image: dpage/pgadmin4:6.10
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@pgadmin.com
      PGADMIN_DEFAULT_PASSWORD: password
      PGADMIN_LISTEN_PORT: 80
    ports:
      - 15432:80
    volumes:
      - pgadmin:/var/lib/pgadmin
    depends_on:
      - database

####################################################################################
#volumes
####################################################################################
volumes:
  postgres:
  pgadmin:
